package org.utl.fruitstore.desktopapp;

import java.awt.BorderLayout;
import javax.swing.UIManager;

/**
 *
 * @author oswal
 */
public class WindowMain extends javax.swing.JFrame {
    
    PanelProducto pnl;
    PanelVendedores pnlV;

    /**
     * Creates new form WindowMain
     */
    public WindowMain() {
        initComponents();
        init_components();
    }
    
    private void init_components(){
        pnl = new PanelProducto(panelPrincipal);
        pnlV = new PanelVendedores(panelPrincipal);
    }
    
    private void cargarModuloProductos(){
        try {
            pnl.cargarTablaProductos();
            pnl.cargarComboBoxCategorias();
            
            //1.- Primero limpiamos el contendor Principal
            panelPrincipal.removeAll();
        
            //2.- Agregamos el panel de Productos al Pincipal
            panelPrincipal.add(pnl, BorderLayout.CENTER);
        
            //3.- Refrescamos el panel Principal
            panelPrincipal.paintAll(panelPrincipal.getGraphics());
        }
        catch (Exception e){
            //e.printStackTrace();
            System.out.println("Ocurrio un error al cargar el Módulo de Productos");
        }
    }
    
    private void cargarModuloVendedores(){
        try {
            pnlV.cargarTablaVendedores();
            
            //1.- Primero limpiamos el contendor Principal
            panelPrincipal.removeAll();
        
            //2.- Agregamos el panel de Productos al Pincipal
            panelPrincipal.add(pnlV, BorderLayout.CENTER);
        
            //3.- Refrescamos el panel Principal
            panelPrincipal.paintAll(panelPrincipal.getGraphics());
        }
        catch (Exception e){
            //e.printStackTrace();
            System.out.println("Ocurrio un error al cargar el Módulo de Vendedores");
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jToolBar1.setFloatable(true);
        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);
        jToolBar1.setMaximumSize(new java.awt.Dimension(4, 56));
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 56));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/24/package.png"))); // NOI18N
        jButton1.setText("Productos");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/32/user.png"))); // NOI18N
        jButton2.setText("Vendedores");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(75, 52));
        jButton2.setMinimumSize(new java.awt.Dimension(75, 52));
        jButton2.setPreferredSize(new java.awt.Dimension(75, 52));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        panelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        panelPrincipal.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cargarModuloProductos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cargarModuloVendedores();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
        public void run(){
            WindowMain wn = new WindowMain();
            wn.pack();
            wn.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
